-- return {
--   'tpope/vim-dadbod',
--   event = 'VeryLazy',
--   dependencies = {
--     'kristijanhusak/vim-dadbod-ui',
--     'kristijanhusak/vim-dadbod-completion',
--   },
--   config = function()
--     vim.api.nvim_create_autocmd('FileType', {
--       pattern = { 'sql', 'mysql', 'plsql' },
--       callback = function()
--         require('cmp').setup.buffer { sources = { { name = 'vim-dadbod-completion' } } }
--       end,
--     })
--
--     require('custom.dadbod-enhancements').setup()
--   end,
-- }
--
return {}
